// <auto-generated />
namespace Task1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class AddDropdownMaster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDropdownMaster));
        
        string IMigrationMetadata.Id
        {
            get { return "202609040504109_AddDropdownMaster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
